name: dostavka
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  line_icons:
  fluttertoast:
  google_nav_bar:

  dio: ^4.0.4
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  path_provider: #Плагин Flutter для поиска часто используемых мест в файловой системе
  flutter_spinkit: ^5.1.0 #звгрузка
  retrofit:
  flutter_bloc: ^7.3.3
  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: #генерировать в/из JSON-код для класса
  hive_generator:
  build_runner:
  flutter_lints:
  retrofit_generator:
  freezed:



flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
